# 2020-10-30

주요내용: 네이버 증권에서 코스피 200 종목 리스트를 크롤링하여 리스트로 저장 후 CSV로 저장까지 완료하였음.
결과물 사진 :

![image](https://github.com/karas741/week05_homework/raw/main/1030.PNG)

추후 해야할 일 : 
- 시가총액 500억 미만 항목 제외
- 종목코드 추가 수집
- 종목코드 순회 하면서 마법공식에 필요한 지표 수집

# 2020-11-03

주요내용: 네이버 증권 사이트를 분석해서 재무재표는 다른 URL을 호출하는것을 확인했습니다. 호출 URL을 호출해서 PER 정보를 긁어오는데 성공했습니다.

문제점: ROA 값을 긁어오는 과정에서 "ID"값이 랜덤으로 변경되어 크롤링 과정에서 오류가 발생합니다.

추후 해야할 일 : 
- ROA 데이터 구하기

# 2020-11-04

주요내용: 11-03에서 발생하는 ROA 문제 해결완료. XPATH 값을 수정하여 해결완료. 이후 PER + ROA 값을 구해서 'magic'키에 추가하고 내림차순으로 정렬함.

```
{'name': '삼성SDI', 'href': 'https://navercomp.wisereport.co.kr/v2/company/c1010001.aspx?cmp_cd=006400', 'present': '459,500', 'diff': '19,500', 'fluc': '+4.43%', 'number': '710,363', 'number2': '325,073', 'number3': 315973, 'magic': 162.8}
{'name': 'LG화학', 'href': 'https://navercomp.wisereport.co.kr/v2/company/c1010001.aspx?cmp_cd=051910', 'present': '656,000', 'diff': '33,000', 'fluc': '+5.30%', 'number': '635,583', 'number2': '413,535', 'number3': 463086, 'magic': 108.9}
{'name': '셀트리온', 'href': 'https://navercomp.wisereport.co.kr/v2/company/c1010001.aspx?cmp_cd=068270', 'present': '259,000', 'diff': '14,500', 'fluc': '+5.93%', 'number': '996,227', 'number2': '254,200', 'number3': 349634, 'magic': 92.4}
{'name': 'NAVER', 'href': 'https://navercomp.wisereport.co.kr/v2/company/c1010001.aspx?cmp_cd=035420', 'present': '283,000', 'diff': '2,500', 'fluc': '-0.88%', 'number': '1,063,658', 'number2': '300,318', 'number3': 464865, 'magic': 70.4}
{'name': 'LG생활건강', 'href': 'https://navercomp.wisereport.co.kr/v2/company/c1010001.aspx?cmp_cd=051900', 'present': '1,517,000', 'diff': '14,000', 'fluc': '-0.91%', 'number': '22,802', 'number2': '34,642', 'number3': 236928, 'magic': 47.7}
{'name': 'SK하이닉스', 'href': 'https://navercomp.wisereport.co.kr/v2/company/c1010001.aspx?cmp_cd=000660', 'present': '81,400', 'diff': '1,800', 'fluc': '+2.26%', 'number': '2,049,009', 'number2': '165,393', 'number3': 592594, 'magic': 28.8}
{'name': '현대차', 'href': 'https://navercomp.wisereport.co.kr/v2/company/c1010001.aspx?cmp_cd=005380', 'present': '170,500', 'diff': '0', 'fluc': '0.00%', 'number': '994,028', 'number2': '169,634', 'number3': 364304, 'magic': 25.7}
{'name': '삼성전자', 'href': 'https://navercomp.wisereport.co.kr/v2/company/c1010001.aspx?cmp_cd=005930', 'present': '58,800', 'diff': '1,400', 'fluc': '+2.44%', 'number': '14,862,764', 'number2': '868,473', 'number3': 3510232, 'magic': 24.2}
```

문제점: 버튼 클릭 후 실시간으로 가지고 오기에는 데이터가 방대하고 느려서 문제가 발생함. 
따라서, 데일리로 자동 호출시켜 DB로 저장한 후 그 값을 화면에 출력하는 로직으로 변경해야함.

첫 페이지 이후 네트워크 오류가 출력됨.

```

Traceback (most recent call last):
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\urllib3\connection.py", line 187, in connect
    conn = self._new_conn()
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000116A48C9850>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\user\Desktop\sparta\last\quant\app.py", line 59, in create_stock
    crawl_stock()
  File "C:\Users\user\Desktop\sparta\last\quant\app.py", line 119, in crawl_stock
    driver.get(stockDict['href'])
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\urllib3\request.py", line 79, in request
    return self.request_encode_body(
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\urllib3\request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\urllib3\poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\urllib3\connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\urllib3\connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\urllib3\connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\user\Desktop\sparta\last\quant\venv\Lib\site-packages\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=59434): Max retries exceeded with url: /session/93abf67fd4e8dc516f08bdff198e560f/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000116A48C9850>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))
```

추후 해야할 일 : 
- 화면 출력
